"""Format v2 read-only mirror documents: ``.report.yml``, ``project.md``, ``.book.yml``,
``.chapter.yml``, ``.grison/library/.shelves/*.yml``.

Every one of these is regenerated by grison on every sync and never hand-edited — their
real integrity guard is the content-digest check in :mod:`grison.validator.mirrors`
(``WS-009``), not the schema here. The schemas below exist so a mirror that's plain
malformed (corrupted, truncated, hand-typed from scratch before a first sync ever ran
and left no digest to compare against) still fails with a precise message instead of an
unhandled exception (``WS-010``) — and so ``dump(parse(x)) == x`` holds for grison's own
generator, which is what actually matters here (these files are never meant to be
hand-authored).

``description``/``tags`` on the book/chapter/shelf mirrors are new in format v2 (not
populated by today's sync — a later step fills them from BookStack); the schema accepts
them now so the engine step doesn't also need to touch the format layer.

``project.md`` carries free-form regenerated prose (scope, objectives, targets, white
cards — see :mod:`grison.remote.repmap`'s ``project_context_to_md``), not simple
key/value structure, so its model is an opaque body wrapper: there is nothing here
to validate beyond "did it parse as text at all", which is always true.
"""

from __future__ import annotations

from pathlib import Path

import yaml
from pydantic import BaseModel, ConfigDict, ValidationError

from grison.formats.common import FormatError, translate_validation_error


class _Base(BaseModel):
    model_config = ConfigDict(extra="forbid")


class ClientMeta(_Base):
    id: int | None = None
    name: str | None = None
    short_name: str | None = None


class ProjectMeta(_Base):
    id: int | None = None
    client: ClientMeta = ClientMeta()
    start_date: str | None = None
    end_date: str | None = None


class StatusMeta(_Base):
    complete: bool | None = None
    archived: bool | None = None
    delivered: bool | None = None


class DatesMeta(_Base):
    creation: str | None = None
    last_update: str | None = None


class ReportMetaDoc(_Base):
    """``.report.yml`` — plain YAML, no frontmatter fence (see :mod:`grison.remote.repmap`'s
    ``meta_to_yaml``, which dumps it via ``fm.dump_yaml``, not ``fm.dump``)."""

    title: str = ""
    project: ProjectMeta = ProjectMeta()
    status: StatusMeta = StatusMeta()
    dates: DatesMeta = DatesMeta()


class BookMirrorDoc(_Base):
    """``<book>/.book.yml``."""

    name: str = ""
    slug: str = ""
    description: str = ""
    tags: list[str] = []
    shelves: list[str] = []


class ChapterMirrorDoc(_Base):
    """``<book>/<chapter>/.chapter.yml``."""

    name: str = ""
    slug: str = ""
    description: str = ""
    tags: list[str] = []
    priority: int | None = None


class ShelfMirrorDoc(_Base):
    """``.shelves/<slug>.yml``."""

    name: str = ""
    slug: str = ""
    description: str = ""
    tags: list[str] = []
    books: list[str] = []


class ProjectContextDoc(_Base):
    """``project.md`` — opaque regenerated prose; see module docstring."""

    body: str = ""


def _parse_yaml_model(text: str, model: type[_Base]) -> object:
    try:
        raw = yaml.safe_load(text) or {}
    except yaml.YAMLError as e:
        raise FormatError("bad_yaml", str(e)) from e
    if not isinstance(raw, dict):
        raise FormatError("bad_yaml", "top level must be a mapping")
    try:
        return model.model_validate(raw)
    except ValidationError as e:
        raise translate_validation_error(e, text=text, fenced=False) from e


def _dump_yaml_model(doc: _Base) -> str:
    return yaml.safe_dump(doc.model_dump(mode="json"), sort_keys=False, allow_unicode=True)


def parse_report_meta(text: str, *, path: Path) -> ReportMetaDoc:
    del path
    doc = _parse_yaml_model(text, ReportMetaDoc)
    assert isinstance(doc, ReportMetaDoc)
    return doc


def dump_report_meta(doc: ReportMetaDoc) -> str:
    return _dump_yaml_model(doc)


def parse_book_mirror(text: str, *, path: Path) -> BookMirrorDoc:
    del path
    doc = _parse_yaml_model(text, BookMirrorDoc)
    assert isinstance(doc, BookMirrorDoc)
    return doc


def dump_book_mirror(doc: BookMirrorDoc) -> str:
    return _dump_yaml_model(doc)


def parse_chapter_mirror(text: str, *, path: Path) -> ChapterMirrorDoc:
    del path
    doc = _parse_yaml_model(text, ChapterMirrorDoc)
    assert isinstance(doc, ChapterMirrorDoc)
    return doc


def dump_chapter_mirror(doc: ChapterMirrorDoc) -> str:
    return _dump_yaml_model(doc)


def parse_shelf_mirror(text: str, *, path: Path) -> ShelfMirrorDoc:
    del path
    doc = _parse_yaml_model(text, ShelfMirrorDoc)
    assert isinstance(doc, ShelfMirrorDoc)
    return doc


def dump_shelf_mirror(doc: ShelfMirrorDoc) -> str:
    return _dump_yaml_model(doc)


def parse_project_context(text: str, *, path: Path) -> ProjectContextDoc:
    del path
    return ProjectContextDoc(body=text)


def dump_project_context(doc: ProjectContextDoc) -> str:
    return doc.body
