"""BookStack book/chapter/shelf structure: read-only mirrors (``.book.yml`` /
``.chapter.yml`` / ``.shelves/*.yml``) plus creating a BookStack book/chapter for a
brand-new local directory (BRIEF's wiki-location section: "new book/chapter
directories ARE allowed").

Deliberately NOT routed through :mod:`grison.engine.classify`/``apply`` — a book/
chapter/shelf mirror never collides, never moves, and is never force-resolved; it is
either regenerated (remote changed, local copy unedited) or left alone (local hand-
edit — the validator's WS-009 is the actual enforcement; see BRIEF D3/D6 and
ENGINE.md's read-only-record-type note). This keeps the shape close to what the
module it replaces (`grison/remote/methodology.py`) already did, adapted to the v2
mirror schema and the engine's own state layer (``.grison/state/mirrors.json``, not
the old ``.grison/mirrors.json``).

The actual "regenerate if unedited, leave alone if hand-edited" guard is
:func:`grison.engine.mirrors.write_mirror_guarded` — a small shared helper so the
next read-only adapter (the REPORTS adapter's own project.md/index.md mirrors) does
not have to re-implement this pattern; see that module's docstring for the rule
itself. This module only decides WHEN to regenerate (its own witness check) and
translates the guard's result into :class:`StructureResult` and an event.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from grison.adapters._bs_common import BSContext, slugify
from grison.engine.mirrors import MirrorWrite, write_mirror_guarded
from grison.engine.model import RemoteRecord
from grison.engine.state import StateStore
from grison.engine.undo import Snapshot, UndoOp
from grison.formats import mirrors as mirrors_fmt
from grison.index import Index, IndexKind
from grison.remote.bookstack import BookStackClient, BookStackError

_MIRROR_HEADER = "# generated by grison — do not edit; edits here are discarded on the next sync\n"
_RECYCLE_REASON = "in the BookStack recycle bin, recoverable there"


class BookUndoAdapter:
    """Exactly :class:`~grison.engine.adapter.CreateUndoAdapter` (no more) for
    ``grison undo`` to reverse a book *creation* (``sync_structure``'s only write to
    this kind) — a book is only ever created, never pushed or deleted, through the
    engine, so there is no pre-image to restore, and this deliberately has no
    ``restore`` method at all: the undo engine's own types (``CreateUndoAdapter`` vs.
    ``RestorableUndoAdapter``) make asking this adapter to restore a pre-image
    unrepresentable, rather than a method that would exist only to raise."""

    kind = "bs.book"

    def __init__(self, client: BookStackClient) -> None:
        self.client = client

    def refetch(self, ctx: object, id: int) -> RemoteRecord | None:
        try:
            detail = self.client.fetch_book(id)
        except BookStackError:
            return None
        return RemoteRecord(id=id, data=detail, witness={})

    def delete(self, ctx: object, id: int) -> None:
        self.client.delete_book(id)


class ChapterUndoAdapter:
    """Sibling of :class:`BookUndoAdapter` for chapter creation."""

    kind = "bs.chapter"

    def __init__(self, client: BookStackClient) -> None:
        self.client = client

    def refetch(self, ctx: object, id: int) -> RemoteRecord | None:
        try:
            detail = self.client.fetch_chapter(id)
        except BookStackError:
            return None
        return RemoteRecord(id=id, data=detail, witness={})

    def delete(self, ctx: object, id: int) -> None:
        self.client.delete_chapter(id)


@dataclass
class StructureResult:
    created_books: list[str] = field(default_factory=list)
    created_chapters: list[str] = field(default_factory=list)
    materialized: list[str] = field(default_factory=list)
    skipped: list[tuple[str, str]] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


def _book_dirs(root: Path) -> list[Path]:
    base = root / "methodology" / "library"
    if not base.is_dir():
        return []
    return sorted(p for p in base.iterdir() if p.is_dir() and p.name != ".shelves")


def _chapter_dirs(book_dir: Path) -> list[Path]:
    return sorted(p for p in book_dir.iterdir() if p.is_dir() and p.name != "images")


def _write_mirror_guarded(
    root: Path, rel_path: str, text: str, mirrors: dict[str, str], result: StructureResult,
    *, dry_run: bool, on_event: Callable[[str], None] | None,
) -> None:
    """Adapts :func:`grison.engine.mirrors.write_mirror_guarded`'s result onto this
    module's own :class:`StructureResult`/event shape."""
    outcome = write_mirror_guarded(root, rel_path, text, mirrors, dry_run=dry_run)
    if outcome.outcome is MirrorWrite.UNCHANGED:
        return
    if outcome.outcome is MirrorWrite.HAND_EDITED:
        assert outcome.message is not None
        result.skipped.append((rel_path, outcome.message))
        if on_event:
            on_event(f"skip {rel_path}: {outcome.message}")
        return
    result.materialized.append(rel_path)
    if on_event:
        verb = "would mirror" if outcome.outcome is MirrorWrite.WOULD_WRITE else "mirror"
        on_event(f"{verb} {rel_path}")


def _witness_unchanged(state: StateStore, kind: str, id: int, updated_at: str | None) -> bool:
    st = state.get(kind, id)
    return st is not None and st.witness.get("updated_at") == updated_at


def sync_structure(  # noqa: PLR0912, PLR0913, PLR0915
    root: Path, ctx: BSContext, index: Index, state: StateStore, snapshot: Snapshot,
    *, dry_run: bool = False, on_event: Callable[[str], None] | None = None,
) -> StructureResult:
    """Create any missing book/chapter on BookStack for a new local directory, then
    (re)generate every book/chapter/shelf mirror. Call before syncing pages — pages
    resolve their parent by slug against ``ctx.books``/``ctx.chapters``, which this
    function refreshes after any create."""
    result = StructureResult()
    recycled_book_ids = {
        e["deletable_id"] for e in ctx.client.fetch_recycle_bin()
        if e.get("deletable_type") == "book"
    }
    recycled_chapter_ids = {
        e["deletable_id"] for e in ctx.client.fetch_recycle_bin()
        if e.get("deletable_type") == "chapter"
    }

    created_any = False
    for book_dir in _book_dirs(root):
        book = ctx.books_by_slug.get(book_dir.name)
        if book is None:
            if dry_run:
                result.created_books.append(book_dir.name)
                if on_event:
                    on_event(f"would create book {book_dir.name}")
                continue
            try:
                rec = ctx.client.create_book(name=book_dir.name)
            except Exception as e:  # noqa: BLE001 — isolate this book, keep going
                result.errors.append(f"{book_dir}: could not create book: {e}")
                continue
            snapshot.record(UndoOp(kind="bs.book", outcome="create", id=rec["id"],
                                   path=f"methodology/library/{book_dir.name}"))
            result.created_books.append(book_dir.name)
            created_any = True
            if on_event:
                on_event(f"create book {book_dir.name}")

    if created_any:
        ctx.refresh()

    created_any = False
    for book_dir in _book_dirs(root):
        book = ctx.books_by_slug.get(book_dir.name)
        if book is None:
            continue  # creation failed above; already reported
        for chapter_dir in _chapter_dirs(book_dir):
            if (book["id"], chapter_dir.name) in ctx.chapters_by_book_slug:
                continue
            rel = f"methodology/library/{book_dir.name}/{chapter_dir.name}"
            if dry_run:
                result.created_chapters.append(rel)
                if on_event:
                    on_event(f"would create chapter {rel}")
                continue
            try:
                rec = ctx.client.create_chapter(book_id=book["id"], name=chapter_dir.name)
            except Exception as e:  # noqa: BLE001
                result.errors.append(f"{chapter_dir}: could not create chapter: {e}")
                continue
            snapshot.record(UndoOp(kind="bs.chapter", outcome="create", id=rec["id"], path=rel))
            result.created_chapters.append(rel)
            created_any = True
            if on_event:
                on_event(f"create chapter {rel}")

    if created_any:
        ctx.refresh()

    mirrors = state.load_mirrors()

    # --- shelves -------------------------------------------------------------
    shelf_books: dict[int, list[str]] = {}
    for shelf in ctx.client.fetch_shelves():
        if not _witness_unchanged(state, "bs.shelf", shelf["id"], shelf.get("updated_at")):
            detail = ctx.client.fetch_shelf(shelf["id"])
            state.put("bs.shelf", shelf["id"], base=None,
                      witness={"updated_at": shelf.get("updated_at")})
        else:
            detail = None
        if detail is None:
            continue  # unchanged since last sync — mirror (if any) already reflects it
        ordered_books = [b.get("slug") or str(b["id"]) for b in detail.get("books") or []]
        for b in detail.get("books") or []:
            shelf_books.setdefault(b["id"], []).append(shelf["slug"])
        shelf_doc = mirrors_fmt.ShelfMirrorDoc(
            name=detail.get("name") or shelf.get("name", ""), slug=shelf["slug"],
            description=detail.get("description") or "",
            tags=[f"{t['name']}:{t['value']}" if t.get("value") else t["name"]
                 for t in detail.get("tags") or []],
            books=ordered_books,
        )
        text = _MIRROR_HEADER + mirrors_fmt.dump_shelf_mirror(shelf_doc)
        rel = f"methodology/library/.shelves/{shelf['slug']}.yml"
        _write_mirror_guarded(root, rel, text, mirrors, result, dry_run=dry_run,
                              on_event=on_event)
        index.set(rel, IndexKind.BS_SHELF, shelf["id"])

    # --- books -----------------------------------------------------------------
    for book in ctx.books:
        index.set(f"methodology/library/{book['slug']}", IndexKind.BS_BOOK, book["id"])
        if not _witness_unchanged(state, "bs.book", book["id"], book.get("updated_at")):
            detail = ctx.client.fetch_book(book["id"])
            state.put("bs.book", book["id"], base=None,
                      witness={"updated_at": book.get("updated_at")})
        else:
            detail = None
        if detail is None:
            continue
        book_doc = mirrors_fmt.BookMirrorDoc(
            name=detail.get("name", ""), slug=book["slug"],
            description=detail.get("description") or "",
            tags=[f"{t['name']}:{t['value']}" if t.get("value") else t["name"]
                 for t in detail.get("tags") or []],
            shelves=shelf_books.get(book["id"], []),
        )
        text = _MIRROR_HEADER + mirrors_fmt.dump_book_mirror(book_doc)
        rel = f"methodology/library/{book['slug']}/.book.yml"
        _write_mirror_guarded(root, rel, text, mirrors, result, dry_run=dry_run,
                              on_event=on_event)

    # --- chapters ----------------------------------------------------------------
    books_by_id = ctx.books_by_id
    for chapter in ctx.chapters:
        book = books_by_id.get(chapter["book_id"])
        if book is None:
            continue
        rel_dir = f"methodology/library/{book['slug']}/{chapter['slug']}"
        index.set(rel_dir, IndexKind.BS_CHAPTER, chapter["id"])
        if not _witness_unchanged(state, "bs.chapter", chapter["id"], chapter.get("updated_at")):
            detail = ctx.client.fetch_chapter(chapter["id"])
            state.put("bs.chapter", chapter["id"], base=None,
                      witness={"updated_at": chapter.get("updated_at")})
        else:
            detail = None
        if detail is None:
            continue
        chapter_doc = mirrors_fmt.ChapterMirrorDoc(
            name=detail.get("name", ""), slug=chapter["slug"],
            description=detail.get("description") or "",
            tags=[f"{t['name']}:{t['value']}" if t.get("value") else t["name"]
                 for t in detail.get("tags") or []],
            priority=chapter.get("priority"),
        )
        text = _MIRROR_HEADER + mirrors_fmt.dump_chapter_mirror(chapter_doc)
        rel = f"{rel_dir}/.chapter.yml"
        _write_mirror_guarded(root, rel, text, mirrors, result, dry_run=dry_run,
                              on_event=on_event)

    # --- recycle-bin awareness: an indexed book/chapter dir whose id vanished from
    # the live lists but is recoverable in the recycle bin is reported, not treated
    # as gone (ENGINE.md / BRIEF B "recycle bin awareness").
    live_book_ids = {b["id"] for b in ctx.books}
    live_chapter_ids = {c["id"] for c in ctx.chapters}
    for idx_path, irec in sorted(index.records.items()):
        if irec.kind is IndexKind.BS_BOOK and irec.id not in live_book_ids:
            reason = _RECYCLE_REASON if irec.id in recycled_book_ids else "book no longer exists"
            result.skipped.append((idx_path, reason))
        elif irec.kind is IndexKind.BS_CHAPTER and irec.id not in live_chapter_ids:
            reason = (
                _RECYCLE_REASON if irec.id in recycled_chapter_ids else "chapter no longer exists"
            )
            result.skipped.append((idx_path, reason))

    if not dry_run:
        state.save_mirrors(mirrors)
    return result


def slugify_dirname(name: str) -> str:
    """Re-exported for callers that need a book/chapter directory's expected slug
    without importing the private common module directly."""
    return slugify(name)
