"""Read-only mirror integrity: ``.report.yml``, ``project.md``, ``notes/*.md`` (the
indexed ones), ``.book.yml``, ``.chapter.yml``, ``.shelves/*.yml`` — plus (D11)
grison's other owned, regenerated-in-place files: ``.grison/SPEC.md``,
``.grison/templates/*``, ``CLAUDE.md``, ``.claude/settings.json``.

These files are regenerated by grison (the sync engine for the wiki/report mirrors,
:mod:`grison.scaffold` for the D11 ones) and never hand-edited. Both write through
:class:`grison.engine.state.StateStore` — ONE writer, ONE serialization, for
``.grison/state/mirrors.json`` — this module is just the digest-bookkeeping API on
top of it (:func:`record_digest`/:func:`expected_digest`), so a caller never has to
know it's the same file the engine's own mirror bookkeeping (structure mirrors) also
reads/writes.

State key: ``.grison/state/mirrors.json`` — a JSON object mapping a workspace-relative,
POSIX-separated path to the ``sha256:<hex>`` digest (:func:`grison.hashing.digest_text`
over the exact UTF-8 text grison wrote) of that path's content as of the last time
grison generated it. Whoever (re)writes a mirror/owned file must update this entry in
the same write; a path with no entry here has never been generated by this grison, so
:func:`expected_digest` returns ``None`` and the caller treats the check as passing
(nothing to compare against yet — brief D3/D13: a fresh-but-not-yet-synced workspace
must not be treated as corrupt).
"""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

from grison.engine.state import StateStore

STATE_RELATIVE_PATH = ".grison/state/mirrors.json"


def _clean(mirrors: Mapping[str, object]) -> dict[str, str]:
    return {k: v for k, v in mirrors.items() if isinstance(k, str) and isinstance(v, str)}


def record_digest(root: Path, path: str, digest: str) -> None:
    """Record ``path``'s current digest as grison's own generated content, merging
    into whatever is already recorded (a corrupt or missing file starts fresh rather
    than failing — this is bookkeeping, never the source of truth for whether a
    document is valid). A no-op — the file is NOT rewritten — when ``digest`` already
    matches what's recorded, so calling this on every run (as :mod:`grison.scaffold`
    does, to keep the baseline current) doesn't touch ``mirrors.json`` on every
    ``grison sync``/``parse``/``scaffold``, only when something actually changed.
    Used by :mod:`grison.scaffold` to mark a freshly (re)generated file (e.g.
    ``CLAUDE.md``) as clean against the same digest :func:`expected_digest` (and
    ``WS-009``) reads back."""
    store = StateStore(root)
    state = _clean(store.load_mirrors())
    if state.get(path) == digest:
        return
    state[path] = digest
    store.save_mirrors(state)


def expected_digest(root: Path, path: str) -> str | None:
    """The digest grison last recorded for ``path`` (workspace-relative, POSIX,
    forward-slashed), or ``None`` if nothing is recorded yet — a missing/unreadable/
    malformed state file, or one with no entry for this path, are all treated the
    same way (see module docstring): there is nothing to compare against, so the
    caller's check passes."""
    return _clean(StateStore(root).load_mirrors()).get(path)
