"""Read-only mirror integrity: ``.report.yml``, ``project.md``, ``notes/*.md`` (the
indexed ones), ``.book.yml``, ``.chapter.yml``, ``.shelves/*.yml``.

These files are regenerated by the sync engine on every run and never hand-edited.
The engine (a later step) is the only writer of the state key this module reads —
this module just defines the read side + the key, so the format-v2 contracts land
before the engine does.

State key: ``.grison/state/mirrors.json`` — a JSON object mapping a workspace-relative,
POSIX-separated path to the ``sha256:<hex>`` digest (:func:`grison.hashing.digest_text`
over the exact UTF-8 text grison wrote) of that path's content as of the last time
grison generated it. The engine must update this entry every time it (re)writes a
mirror file, in the same write; a path with no entry here has never been generated by
this grison, so :func:`expected_digest` returns ``None`` and the caller treats the
check as passing (nothing to compare against yet — brief D3/D13: a fresh-but-not-yet-
synced workspace must not be treated as corrupt).
"""

from __future__ import annotations

import json
from pathlib import Path

STATE_RELATIVE_PATH = ".grison/state/mirrors.json"


def expected_digest(root: Path, path: str) -> str | None:
    """The digest grison last recorded for ``path`` (workspace-relative, POSIX,
    forward-slashed), or ``None`` if nothing is recorded yet — a missing/unreadable/
    malformed state file, or one with no entry for this path, are all treated the
    same way (see module docstring): there is nothing to compare against, so the
    caller's check passes."""
    state_path = root / STATE_RELATIVE_PATH
    if not state_path.exists():
        return None
    try:
        data = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict):
        return None
    value = data.get(path)
    return value if isinstance(value, str) else None
