"""Read-only mirror integrity: ``.report.yml``, ``project.md``, ``notes/*.md`` (the
indexed ones), ``.book.yml``, ``.chapter.yml``, ``.shelves/*.yml``.

These files are regenerated by the sync engine on every run and never hand-edited.
The engine (a later step) is the only writer of the state key this module reads —
this module just defines the read side + the key, so the format-v2 contracts land
before the engine does.

State key: ``.grison/state/mirrors.json`` — a JSON object mapping a workspace-relative,
POSIX-separated path to the ``sha256:<hex>`` digest (:func:`grison.hashing.digest_text`
over the exact UTF-8 text grison wrote) of that path's content as of the last time
grison generated it. The engine must update this entry every time it (re)writes a
mirror file, in the same write; a path with no entry here has never been generated by
this grison, so :func:`expected_digest` returns ``None`` and the caller treats the
check as passing (nothing to compare against yet — brief D3/D13: a fresh-but-not-yet-
synced workspace must not be treated as corrupt).
"""

from __future__ import annotations

import json
from pathlib import Path

from grison.fsio import atomic_write_text

STATE_RELATIVE_PATH = ".grison/state/mirrors.json"


def _load(root: Path) -> dict[str, str]:
    state_path = root / STATE_RELATIVE_PATH
    if not state_path.exists():
        return {}
    try:
        data = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    if not isinstance(data, dict):
        return {}
    return {k: v for k, v in data.items() if isinstance(k, str) and isinstance(v, str)}


def record_digest(root: Path, path: str, digest: str) -> None:
    """Record ``path``'s current digest as grison's own generated content, merging
    into whatever is already recorded (a corrupt or missing file starts fresh rather
    than failing — this is bookkeeping, never the source of truth for whether a
    document is valid). ``.grison/state/`` is private, so this is written 0600 like
    every other file under it. Used by :mod:`grison.scaffold` to mark a freshly
    (re)generated file (e.g. ``CLAUDE.md``) as clean against the same digest
    :func:`expected_digest` (and ``WS-009``) reads back."""
    state = _load(root)
    state[path] = digest
    state_path = root / STATE_RELATIVE_PATH
    atomic_write_text(state_path, json.dumps(state, indent=2, sort_keys=True) + "\n", private=True)


def expected_digest(root: Path, path: str) -> str | None:
    """The digest grison last recorded for ``path`` (workspace-relative, POSIX,
    forward-slashed), or ``None`` if nothing is recorded yet — a missing/unreadable/
    malformed state file, or one with no entry for this path, are all treated the
    same way (see module docstring): there is nothing to compare against, so the
    caller's check passes."""
    state_path = root / STATE_RELATIVE_PATH
    if not state_path.exists():
        return None
    try:
        data = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict):
        return None
    value = data.get(path)
    return value if isinstance(value, str) else None
